data_dir: 'data/training/000'
shift_cloud: true
lidar_height: 1.733
num_points: 10000
grid_range: [0, -5, 10, 5] 

# voxel_generator:
# pc_range: [-49.4, -50, -4, 50.6, 50, 4] # cmcdot grid origin is at base_link not the velodyne so have to crop points from 0.6
pc_range: [0,-5,-4,10,5,4] # cmcdot grid origin is at base_link not the velodyne so have to shift cropping points
voxel_size : [.2, .2, 8]
max_points_voxel : 100
max_voxels: 2500
input_features: 3

# model_param
batch_size: 2
lr: 0.01
momentum: 0.9
weight_decay: 0.0005
epochs: 120
use_norm: false
clip: 0.25 # gradient clipping
max_memory: 4000 # Maximum memory to load at once in MiB

# Voxel Feature Extractor
vfe_filters: [64] # only one filter for now
with_distance: false

# loss_param
alpha: 0.9 # per cell loss
beta: 0.1 # Smoothness loss

# augmentation paramters
keep_original: false
num_rotations: 4
num_height_var: 1
num_noise_var: 1
maxFrontSlope: 5
maxSideTild: 5
maxRotation: 180
maxHeight: .5
noise_coefficient_top: [0,0]
noise_coefficient_bottom: [0,0.6]
noise_min_distance: [0, 5]
noise_density_top: [.1,50]
noise_density_bottom: [.1,50]

# data prepartaion config
frame_step: 2
frames_per_block: 50
num_workers: 10
data_dir: '/work/yw410445/dataset/sequences/'
out_dir: '/work/yw410445/training_data_v2/sequences/'
